In this area we will see how to split the data after they are seperated into features 'X' and Dependent variable vectors 'y'.

For a good model, all the data available is not consumed in the build. Always data is split into training and test sets.
The model is built on the training sets and the predictions are always tested on the test sets.
Test set is also used to evaluate a particular model and calculate the accuracy of the model.

Generally data is divided in to 80% training data and 20% test data. The percentage can also vary depending on the situation.

Data is divided into X_train, X_test and y_train, y_test
Predictions are always done on y_test.

First lets import all the libraries

In [4]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
from sklearn import datasets

A new Library is being introduced here. Sikit-learn. Scikit Learn is a robust library which brings ML into production system.
It provides a range of supervised and unsupervised learning algorithms via a consistent interface in Python.
Sikit-learn uses numpy extensively for high-performance linear algebra and array operations.

In [6]:
# Importing the dataset
dataset = pd.read_csv('Data_Ads.csv')

Import the dataset using 'pd.read_csv' function

X = dataset.iloc[:, [2, 3]].values : implies all rows of columns with index 2 and 3 are passed as features

This is another way of slicing the datasets.
We can also slice the columns and rows by passing the index numbers seperated by ',' comma.

In [13]:
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values

y = dataset.iloc[:, 4].values implies all the rows and the column index 4 which is the last in our case,  will be passed to y

In [15]:
print(X)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]]


In [16]:
print(y)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0]


Once we have our dataset ready, we will split the data into training set and test set

In [11]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

The function used to split is 'train_test_split' which is imported from the Sikit-learn 'Sklearn.model_selection'

Train is used to build and Test is used to evaluate the model or predict
train_test_split is a method to Split arrays or matrices into random train and test subsets

Call the 'train_test_split' function and pass our dataset X,y along with split parameters.
    test_size: Represents the proportion of split. 0.25 means 25% split
    random_state: Controls the shuffling applied to the data before applying the split.
    train_size: Represent the proportion of the dataset to include in the train split
    shuffle: Whether or not to shuffel the data
    stratify: If not none, data is split in stratified fashion.
    

In [11]:
print(X_train)

[[    27  58000]
 [    18  82000]
 [    25  33000]
 [    47  25000]
 [    48  41000]
 [    45  26000]
 [    35  20000]
 [    26  80000]
 [    29  43000]
 [    27  84000]
 [    19  76000]
 [    46  28000]
 [    48  29000]
 [    35  65000]
 [    32 150000]
 [    46  23000]
 [    27  57000]
 [    19  19000]
 [    47  49000]
 [    29  80000]
 [    20  86000]]


In [12]:
print(X_test)

[[   26 43000]
 [   45 22000]
 [   45 22000]
 [   32 18000]
 [   26 52000]
 [   47 20000]
 [   47 30000]
 [   49 28000]]


As the test split is 0.25, 25% of the data is split for testing and 75% for training